workflows:
  android-build:
    name: Android Build Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk
        ANDROID_HOME: /opt/android-sdk-linux
    scripts:
      - name: Set up JDK
        script: |
          sudo apt-get update
          sudo apt-get install openjdk-17-jdk
          java -version
      - name: Set up Android SDK
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/outputs/**/*.apk
